#@TYPE: Machine
#@NAME: RaspberryPi 5 Development Board (64bit)
#@DESCRIPTION: Machine configuration for the RaspberryPi 5 in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi5:"
#require conf/machine/raspberrypi5.conf

#PREFERRED_VERSION_linux-raspberrypi ??= "6.12.%"
#PREFERRED_VERSION_linux-raspberrypi-v7 ??= "${PREFERRED_VERSION_linux-raspberrypi}"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config \
    rpi-eeprom \
    raspi-utils \
    u-boot-env \
    u-boot-fw-utils \
"